apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindie-ms-controller
  labels:
    app: mindie-ms-controller
  namespace: mindie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mindie-ms-controller
  template:
    metadata:
      labels:
        app: mindie-ms-controller
        deploy-name: mindie-ms-controller
    spec:
      terminationGracePeriodSeconds: 0
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1001
      containers:
        - image: mindie:1.0.0-aarch64-800I-A2
          imagePullPolicy: IfNotPresent
          name: mindie-ms-controller
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: "RuntimeDefault"
          startupProbe:
            exec:
              command:
              - bash
              - -c
              - "$CONFIGMAP_PATH/probe.sh startup"
            periodSeconds: 5
            failureThreshold: 100
          readinessProbe:
            exec:
              command:
              - bash
              - -c
              - "$CONFIGMAP_PATH/probe.sh readiness"
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
              - bash
              - -c
              - "$CONFIGMAP_PATH/probe.sh liveness"
            periodSeconds: 5
            timeoutSeconds: 4
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CONFIGMAP_PATH
              value: /mnt/configmap
            - name: CONFIG_PATH
              value: /usr/local/Ascend/pyMotor/conf
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command: ["/bin/bash", "-c", "
              source /mnt/configmap/boot.sh; \n
          "]
          resources:
            requests:
              memory: "2Gi"
              cpu: "4"
            limits:
              memory: "4Gi"
              cpu: "8"
          volumeMounts:
            - name: boot-bash-script
              mountPath: /mnt/configmap/boot.sh
              subPath: boot.sh
            - name: update-config-script
              mountPath: /mnt/configmap/update_config_from_user_config.py
              subPath: update_config_from_user_config.py
            - name: probe-script
              mountPath: /mnt/configmap/probe.sh
              subPath: probe.sh
            - name: probe-status-check-script
              mountPath: /mnt/configmap/probe_status_check.py
              subPath: probe_status_check.py
            - name: get-mgmt-port-script
              mountPath: /mnt/configmap/get_mgmt_port.py
              subPath: get_mgmt_port.py
            - name: user-config
              mountPath: /mnt/configmap/user_config.json
              subPath: user_config.json
            - name: coredump
              mountPath: /var/coredump
            - name: mnt
              mountPath: /mnt
      volumes:
        - name: boot-bash-script
          configMap:
            name: boot-bash-script
            defaultMode: 0550
        - name: update-config-script
          configMap:
            name: update-config-script
            defaultMode: 0640
        - name: probe-script
          configMap:
            name: probe-script
            defaultMode: 0550
        - name: probe-status-check-script
          configMap:
            name: probe-status-check-script
            defaultMode: 0550
        - name: get-mgmt-port-script
          configMap:
            name: get-mgmt-port-script
            defaultMode: 0550
        - name: user-config
          configMap:
            name: user-config
            defaultMode: 0640
        - name: coredump
          hostPath:
            path: /var/coredump
            type: DirectoryOrCreate
        - name: mnt
          hostPath:
            path: /mnt
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mindie-ms-controller
  name: mindie-ms-controller-service
  namespace: mindie
spec:
  ports:
  - port: 57675
    protocol: TCP
    targetPort: 57675
  selector:
    app: mindie-ms-controller
  sessionAffinity: None
  publishNotReadyAddresses: true
  type: ClusterIP
status:
  loadBalancer: {}