apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindie-ms-coordinator
  labels:
    app: mindie-ms-coordinator
  namespace: mindie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mindie-ms-coordinator
  template:
    metadata:
      labels:
        app: mindie-ms-coordinator
    spec:
      terminationGracePeriodSeconds: 0
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1001
      containers:
        - image: mindie:1.0.0-aarch64-800I-A2
          imagePullPolicy: IfNotPresent
          name: mindie-ms-coordinator
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: "RuntimeDefault"
          readinessProbe:
            httpGet:
              path: /readiness
              port: 1026
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
          env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONFIGMAP_PATH
            value: /mnt/configmap
          - name: CONFIG_PATH
            value: /usr/local/Ascend/pyMotor/conf
          command: ["/bin/bash", "-c", "
              source /mnt/configmap/boot.sh; \n
          "]
          resources:
            requests:
              memory: "4Gi"
              cpu: "16"
            limits:
              memory: "8Gi"
              cpu: "64"
          volumeMounts:
          - name: boot-bash-script
            mountPath: /mnt/configmap/boot.sh
            subPath: boot.sh
          - name: update-config-script
            mountPath: /mnt/configmap/update_config_from_user_config.py
            subPath: update_config_from_user_config.py
          - name: user-config
            mountPath: /mnt/configmap/user_config.json
            subPath: user_config.json
          - name: coredump
            mountPath: /var/coredump
          - name: mnt
            mountPath: /mnt
      volumes:
      - name: boot-bash-script
        configMap:
          name: boot-bash-script
          defaultMode: 0550
      - name: update-config-script
        configMap:
          name: update-config-script
          defaultMode: 0640
      - name: user-config
        configMap:
          name: user-config
          defaultMode: 0640
      - name: coredump
        hostPath:
          path: /var/coredump
          type: DirectoryOrCreate
      - name: mnt
        hostPath:
          path: /mnt
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mindie-ms-coordinator
  name: mindie-ms-coordinator-service
  namespace: mindie
spec:
  ports:
    - port: 1026
      protocol: TCP
      targetPort: 1026
  selector:
    app: mindie-ms-coordinator
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mindie-ms-coordinator
  name: mindie-ms-coordinator-infer
  namespace: mindie
spec:
  ports:
    - nodePort: 31015
      port: 1025
      protocol: TCP
      targetPort: 1025
  selector:
    app: mindie-ms-coordinator
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}