#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.

import time
from enum import Enum
from typing import Optional, Dict, Any
from pydantic import BaseModel, Field

from motor.common.resources.endpoint import Endpoint
from motor.common.resources.instance import Instance


class RequestType(Enum):
    OPENAI = "openai"
    TRITON = "triton"
    TGI = "tgi"
    VLLM = "vllm"
    MINDIE = "mindie"


class ReqState(Enum):
    ARRIVE = 'Arrive'               # Request arrive
    P_SCHEDULING = 'P_Scheduling'   # Currently scheduling P instance
    P_ALLOCATED = 'P_Allocated'     # Allocated P instance
    PREFILL_END = 'Prefill End'     # Prefill completed
    FIRST_TOKEN_FINISH = 'First Token Finish'   # First decoded token
    D_SCHEDULING = 'D_Scheduling'   # Currently scheduling D instance
    D_ALLOCATED = 'D_Allocated'     # Allocated D instance
    DECODE_END = 'Decode End'       # Decode completed
    INVALID = 'Invalid'             # Invalid state
    TIMEOUT = 'Timeout'             # Request timeout
    EXCEPTION = 'Exception'         # Request exception
    RECOMPUTE = 'Recompute'         # Recomputation


class RequestInfo(BaseModel):
    req_id: str = Field(..., description="Request ID generated by RequestManager")
    req_data: dict = Field(..., description="Request json content")
    req_len: int = Field(..., description="Request body length")
    api: str = Field(..., description="API need to be forwarded")
    state: ReqState = Field(default=ReqState.ARRIVE, description="Request current status")
    status: dict[ReqState, float] = Field(default={}, description="Request status time")
    
    def __init__(self, **data):
        super().__init__(**data)
        self.status[ReqState.ARRIVE] = time.time()

    def update_state(self, new_state: ReqState):
        self.state = new_state
        self.status[new_state] = time.time()


class ScheduledResource(BaseModel):
    """Represents a scheduled resource with an instance and endpoint"""
    instance: Instance = None
    endpoint: Endpoint = None


class RequestResponse(BaseModel):
    request_id: str
    status: str
    message: Optional[str] = None
    data: Optional[Dict[str, Any]] = None