# -*- coding: utf-8 -*-
# Copyright (c) Huawei Technologies Co., Ltd. 2025-2026. All rights reserved.
# MindIE is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#         http://license.coscl.org.cn/MulanPSL2
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.

import time
from enum import Enum

from pydantic import BaseModel, Field, PrivateAttr

import anyio

from motor.common.resources.instance import PDRole
from motor.coordinator.tracer.tracing import TraceObj


class RequestType(Enum):
    OPENAI = "openai"
    TRITON = "triton"
    TGI = "tgi"
    VLLM = "vllm"
    MINDIE = "mindie"


class ReqState(Enum):
    ARRIVE = 'Arrive'               # Request arrive
    P_SCHEDULING = 'P_Scheduling'   # Currently scheduling P instance
    P_ALLOCATED = 'P_Allocated'     # Allocated P instance
    PREFILL_END = 'Prefill End'     # Prefill completed
    FIRST_TOKEN_FINISH = 'First Token Finish'   # First decoded token
    D_SCHEDULING = 'D_Scheduling'   # Currently scheduling D instance
    D_ALLOCATED = 'D_Allocated'     # Allocated D instance
    DECODE_END = 'Decode End'       # Decode completed
    INVALID = 'Invalid'             # Invalid state
    TIMEOUT = 'Timeout'             # Request timeout
    EXCEPTION = 'Exception'         # Request exception
    RECOMPUTE = 'Recompute'         # Recomputation


class RequestInfo(BaseModel):
    req_id: str = Field(..., description="Request ID generated by RequestManager")
    req_data: dict = Field(..., description="Request json content")
    req_len: int = Field(..., description="Request body length")
    api: str = Field(..., description="API need to be forwarded")
    state: ReqState = Field(default=ReqState.ARRIVE, description="Request current status")
    status: dict[ReqState, float] = Field(default={}, description="Request status time")
    trace_obj: TraceObj = Field(default_factory=TraceObj, description="Tracing object")
    _p_cancel_scope: anyio.CancelScope | None = PrivateAttr(default=None)
    _d_cancel_scope: anyio.CancelScope | None = PrivateAttr(default=None)

    def __init__(self, **data):
        super().__init__(**data)
        self.status[ReqState.ARRIVE] = time.time()
        
    @property
    def is_cancelled(self) -> bool:
        return (self._p_cancel_scope and self._p_cancel_scope.cancel_called) \
            or (self._d_cancel_scope and self._d_cancel_scope.cancel_called)

    def update_state(self, new_state: ReqState):
        self.state = new_state
        self.status[new_state] = time.time()

    def set_cancel_scope(self, cancel_scope: anyio.CancelScope, role: PDRole):
        if role == PDRole.ROLE_P:
            self._p_cancel_scope = cancel_scope
        elif role == PDRole.ROLE_D:
            self._d_cancel_scope = cancel_scope
    
    def cancel_scope(self):
        if self._p_cancel_scope and not self._p_cancel_scope.cancel_called:
            self._p_cancel_scope.cancel()
        if self._d_cancel_scope and not self._d_cancel_scope.cancel_called:
            self._d_cancel_scope.cancel()